language: cpp

addons:
  apt:
    packages:
      - libpcap-dev
      - libboost-all-dev

matrix:
  include:
    - name: "bionic/amd64/gcc"
      os: linux
      compiler: gcc
      dist: bionic
      arch: amd64
    - name: "bionic/arm64/gcc"
      os: linux
      compiler: gcc
      dist: bionic
      arch: arm64
    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
