language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      addons:
        apt:
          packages:
            - libpcap-dev
    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
